import type { EcoleDanse, EcoleType, ParcoursFormation } from './ecoles-data'

type FormationInput = {
  id: string
  nom: string
  type?: EcoleType
  ville: string
  region: string
  adresse?: string
  siteWeb?: string
  parcours: ParcoursFormation[]
  styles?: string[]
  programmes?: string[]
  duree?: string
  statut?: "Public" | "Privé"
  description?: string
}

const formation = ({ type = "Centre de formation", styles = [], programmes, ...data }: FormationInput): EcoleDanse => ({
  ...data,
  type,
  styles,
  programmes: programmes ?? data.parcours,
  niveaux: ["Professionnel"],
  pratiques: ["Formation professionnelle"],
  categorie: "Se former professionnellement",
})

export const formationsProfessionnelles: EcoleDanse[] = [
  formation({ id: "conservatoire-de-paris", nom: "CNSMD de Paris", type: "Établissement supérieur", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.conservatoiredeparis.fr/", parcours: ["Enseignement supérieur", "DNSP", "Supérieur public"], programmes: ["DNSP", "Master danse"], styles: ["Classique", "Contemporain"], statut: "Public" }),
  formation({ id: "ecole-danse-opera-paris", nom: "École de Danse de l’Opéra national de Paris", type: "École", ville: "Nanterre", region: "Île-de-France", siteWeb: "https://www.operadeparis.fr/artistes/ballet/le-junior-ballet", parcours: ["Formation professionnelle", "Préprofessionnel", "Jeune Ballet / Junior Ballet", "Insertion professionnelle", "Danseur interprète", "Professionnalisation"], programmes: ["École de Danse", "Junior Ballet de l’Opéra national de Paris"], styles: ["Classique", "Contemporain"], duree: "Junior Ballet : 2 ans", statut: "Public" }),
  formation({ id: "pspbb", nom: "PSPBB", type: "Établissement supérieur", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.pspbb.fr/", parcours: ["Enseignement supérieur", "DNSP", "Danseur interprète", "Supérieur public"], programmes: ["DNSP danseur jazz"], styles: ["Jazz / modern jazz"], statut: "Public" }),
  formation({ id: "centre-national-danse", nom: "Centre national de la danse", type: "Centre de formation", ville: "Pantin", region: "Île-de-France", siteWeb: "https://www.cnd.fr/", parcours: ["DE", "Formation professionnelle"], programmes: ["Diplôme d’État", "Formation professionnelle continue"], statut: "Public" }),
  formation({ id: "crr-paris-ida-rubinstein", nom: "CRR de Paris – CPES danse", type: "Conservatoire", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.paris.fr/pages/la-danse-au-crr-de-paris-ida-rubinstein-31753", parcours: ["CPES / COP", "Préprofessionnel", "Supérieur public"], programmes: ["CPES danse"], statut: "Public" }),
  formation({ id: "choreia", nom: "Choreia Arts Studio", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.choreia.com/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"], statut: "Privé" }),
  formation({ id: "ridc", nom: "RIDC", type: "Centre de formation", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.ridc-danse.com/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"], programmes: ["Formation du danseur", "EAT", "DE"], styles: ["Contemporain"], statut: "Privé" }),
  formation({ id: "studio-harmonic", nom: "Studio Harmonic", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.studioharmonic.fr/", parcours: ["Formation professionnelle", "DE"], statut: "Privé" }),
  formation({ id: "ifpro-rick-odums", nom: "IFPRO – Centre Rick Odums", type: "Centre de formation", ville: "Paris", region: "Île-de-France", siteWeb: "https://centre-rick-odums.com/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"], styles: ["Jazz / modern jazz"], statut: "Privé" }),
  formation({ id: "academie-internationale-danse", nom: "Académie Internationale de la Danse", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.aicomparis.com/aid-danse/", parcours: ["Formation professionnelle", "EAT", "DE"], statut: "Privé" }),
  formation({ id: "espace-pleiade", nom: "Espace Pléiade", type: "Centre de formation", ville: "Paris", region: "Île-de-France", parcours: ["Formation professionnelle", "DE"], programmes: ["Formation", "DE danse jazz"], styles: ["Jazz / modern jazz"] }),
  formation({ id: "goube-danse-etudes", nom: "European Dance Center / Goubé Danse Études", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.danse-goube-paris.com/", parcours: ["Danse-études", "Danseur interprète", "Formation professionnelle", "DE"], statut: "Privé" }),
  formation({ id: "acts-ecole-danse", nom: "ACTS", type: "Centre de formation", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.acts-dance.com/", parcours: ["Formation professionnelle", "Danseur interprète"], programmes: ["Artiste chorégraphique"], styles: ["Contemporain"], statut: "Privé" }),
  formation({ id: "paris-dance-school", nom: "Paris Dance School", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.parisdanceschool.com/", parcours: ["Danseur interprète", "Formation professionnelle"], programmes: ["Cursus professionnel long"], statut: "Privé" }),
  formation({ id: "juste-debout-school", nom: "Juste Debout School", type: "École", ville: "Paris", region: "Île-de-France", siteWeb: "https://www.juste-debout-school.com/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Street dance", "Hip-hop / danses urbaines"], statut: "Privé" }),
  formation({ id: "studio-massaro", nom: "Studio Massaro", type: "Studio", ville: "Paris", region: "Île-de-France", siteWeb: "https://studio-massaro.fr/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Hip-hop / danses urbaines", "Contemporain"], statut: "Privé" }),
  formation({ id: "neodance-academy", nom: "Neodance Academy", type: "École", ville: "Pantin", region: "Île-de-France", siteWeb: "https://neodanceacademy.com/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Pluridisciplinaire"], duree: "2 ans", statut: "Privé" }),
  formation({ id: "cnsmd-lyon", nom: "CNSMD de Lyon", type: "Établissement supérieur", ville: "Lyon", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.cnsmd-lyon.fr/", parcours: ["Enseignement supérieur", "DNSP", "Danseur interprète", "Jeune Ballet / Junior Ballet", "Insertion professionnelle", "Supérieur public"], programmes: ["DNSP", "Master", "Jeune Ballet"], statut: "Public" }),
  formation({ id: "cfd-desoblique", nom: "CFD Désoblique", ville: "Lyon", region: "Auvergne-Rhône-Alpes", parcours: ["Formation professionnelle", "DE"] }),
  formation({ id: "hallet-eghayan", nom: "Centre Hallet Eghayan", ville: "Lyon", region: "Auvergne-Rhône-Alpes", siteWeb: "https://halleteghayan.com/", parcours: ["Formation professionnelle"], programmes: ["Formation chorégraphique", "Perfectionnement"] }),
  formation({ id: "le-cycle", nom: "Centre Chorégraphique Le Cycle", ville: "Villeurbanne", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.le-cycle.fr/", parcours: ["Formation professionnelle", "Jeune Ballet / Junior Ballet"], programmes: ["Perfectionnement", "Jeune Ballet contemporain"], styles: ["Contemporain"] }),
  formation({ id: "artystik", nom: "Artys’Tik", ville: "Annecy", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.centreartys.com/", parcours: ["Formation professionnelle", "DE"], styles: ["Classique", "Jazz / modern jazz", "Contemporain"] }),
  formation({ id: "la-manufacture-aurillac", nom: "La Manufacture", ville: "Aurillac", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.la-manufacture.org/", parcours: ["Danseur interprète", "Formation professionnelle", "DE"], programmes: ["Artiste danseur", "DE"], styles: ["Contemporain"] }),
  formation({ id: "asap-compagnie-soon", nom: "ASAP – Compagnie Soon", type: "Compagnie", ville: "Clermont-Ferrand", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.ciesoon.com/", parcours: ["Formation professionnelle", "Insertion professionnelle"], programmes: ["Professionnalisation du danseur"] }),
  formation({ id: "boomstructur", nom: "Boom’Structur CDCN", ville: "Clermont-Ferrand", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.boomstructur.fr/", parcours: ["Insertion professionnelle"], programmes: ["Accompagnement", "Professionnalisation", "Insertion"] }),
  formation({ id: "esmd-hauts-de-france", nom: "ESMD Hauts-de-France", type: "Établissement supérieur", ville: "Lille", region: "Hauts-de-France", siteWeb: "https://www.esmd.fr/", parcours: ["Enseignement supérieur", "DE", "EAT", "Supérieur public"], statut: "Public" }),
  formation({ id: "cpes-lille-roubaix", nom: "CPES danse Lille–Roubaix", type: "Conservatoire", ville: "Lille / Roubaix", region: "Hauts-de-France", siteWeb: "https://conservatoire.ville-roubaix.fr/", parcours: ["CPES / COP", "Préprofessionnel", "Supérieur public"], statut: "Public" }),
  formation({ id: "esal-metz", nom: "ESAL – Pôle Musique et Danse", type: "Établissement supérieur", ville: "Metz", region: "Grand Est", siteWeb: "https://www.esal-pmd.fr/", parcours: ["Enseignement supérieur", "DE", "Supérieur public"], statut: "Public" }),
  formation({ id: "epas-macon", nom: "EPAS", ville: "Mâcon", region: "Bourgogne-Franche-Comté", siteWeb: "https://epas.pro/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Jazz / modern jazz", "Comédie musicale"], statut: "Privé" }),
  formation({ id: "conservatoire-tours", nom: "Conservatoire de Tours", type: "Conservatoire", ville: "Tours", region: "Centre-Val de Loire", siteWeb: "https://www.conservatoiretours.fr/", parcours: ["Préprofessionnel", "Formation professionnelle", "Supérieur public"], programmes: ["Cycle préparatoire", "Formation professionnelle initiale"], statut: "Public" }),
  formation({ id: "conservatoire-rennes", nom: "Conservatoire de Rennes", type: "Conservatoire", ville: "Rennes", region: "Bretagne", siteWeb: "https://conservatoire-rennes.fr/", parcours: ["Préprofessionnel", "Supérieur public"], programmes: ["Cycle à orientation professionnelle"], statut: "Public" }),
  formation({ id: "cndc-angers", nom: "CNDC", type: "Établissement supérieur", ville: "Angers", region: "Pays de la Loire", siteWeb: "https://www.cndc.fr/", parcours: ["Enseignement supérieur", "DNSP", "Danseur interprète", "Supérieur public"], styles: ["Contemporain"], statut: "Public" }),
  formation({ id: "pont-superieur", nom: "Le Pont Supérieur", type: "Établissement supérieur", ville: "Nantes", region: "Pays de la Loire", siteWeb: "https://www.lepontsuperieur.eu/", parcours: ["Enseignement supérieur", "DE", "Supérieur public"], statut: "Public" }),
  formation({ id: "ecole-adeline-miller", nom: "École Adeline Miller", type: "École", ville: "Nantes", region: "Pays de la Loire", siteWeb: "https://www.adelinemiller.com/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT"], statut: "Privé" }),
  formation({ id: "ecole-nationale-cabaret", nom: "École Nationale de Cabaret", type: "École", ville: "Nantes", region: "Pays de la Loire", siteWeb: "https://ecole-nationale-cabaret.com/", parcours: ["Formation professionnelle", "Danseur interprète"], styles: ["Cabaret / music-hall"], statut: "Privé" }),
  formation({ id: "pesmd-bordeaux", nom: "PESMD Bordeaux Nouvelle-Aquitaine", type: "Établissement supérieur", ville: "Bordeaux", region: "Nouvelle-Aquitaine", siteWeb: "https://www.pesmd.com/", parcours: ["Enseignement supérieur", "DE", "Supérieur public"], statut: "Public" }),
  formation({ id: "cf-adage", nom: "CF ADAGE", ville: "Bordeaux", region: "Nouvelle-Aquitaine", siteWeb: "https://www.cfadage33.fr/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Contemporain", "Hip-hop / danses urbaines"], duree: "2 ans" }),
  formation({ id: "jeune-ballet-aquitaine", nom: "Jeune Ballet d’Aquitaine", type: "Compagnie", ville: "Bordeaux", region: "Nouvelle-Aquitaine", siteWeb: "https://www.jeuneballetdaquitaine.com/", parcours: ["Jeune Ballet / Junior Ballet", "Danseur interprète", "Insertion professionnelle"] }),
  formation({ id: "isdat", nom: "isdaT", type: "Établissement supérieur", ville: "Toulouse", region: "Occitanie", siteWeb: "https://www.isdat.fr/", parcours: ["Enseignement supérieur", "DE", "Supérieur public"], statut: "Public" }),
  formation({ id: "james-carles", nom: "Centre Chorégraphique James Carlès", ville: "Toulouse", region: "Occitanie", siteWeb: "https://jamescarles.com/", parcours: ["Danseur interprète", "EAT", "DE", "Jeune Ballet / Junior Ballet"], programmes: ["Formation danseur interprète", "EAT", "DE", "Junior Ballet", "Chorégraphe"] }),
  formation({ id: "art-dance-international", nom: "Art Dance International", ville: "Toulouse", region: "Occitanie", siteWeb: "https://www.artdance.fr/", parcours: ["Formation professionnelle", "Danseur interprète", "EAT", "DE"] }),
  formation({ id: "toulouse-danse-formation", nom: "Toulouse Danse Formation", ville: "Toulouse", region: "Occitanie", siteWeb: "https://tdf-danse.fr/", parcours: ["Danseur interprète", "Formation professionnelle"], duree: "2 ans" }),
  formation({ id: "vm-ballet", nom: "VM Ballet", type: "École", ville: "Toulouse", region: "Occitanie", siteWeb: "https://vmballet.com/", parcours: ["Formation professionnelle"], styles: ["Classique"] }),
  formation({ id: "extensions-place-danse", nom: "Extensions – La Place de la Danse CDCN", ville: "Toulouse", region: "Occitanie", siteWeb: "https://laplacedeladanse.com/", parcours: ["Insertion professionnelle"], programmes: ["Perfectionnement", "Insertion professionnelle"], styles: ["Contemporain"] }),
  formation({ id: "epsedanse", nom: "EPSEDANSE", ville: "Montpellier", region: "Occitanie", siteWeb: "https://www.epsedanse.com/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"] }),
  formation({ id: "creps-montpellier", nom: "CREPS Montpellier", type: "Centre de formation", ville: "Montpellier", region: "Occitanie", siteWeb: "https://www.creps-montpellier.org/", parcours: ["DE", "Supérieur public"], styles: ["Classique", "Contemporain", "Jazz / modern jazz"], statut: "Public" }),
  formation({ id: "dna-dance-area", nom: "DNA Dance Area", ville: "Montpellier", region: "Occitanie", siteWeb: "https://www.dna-dancearea.com/", parcours: ["Danseur interprète", "Formation professionnelle"] }),
  formation({ id: "dynamic-studio", nom: "Dynamic Studio", type: "Studio", ville: "Perpignan", region: "Occitanie", siteWeb: "https://dynamic-studio.fr/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT"] }),
  formation({ id: "pnsd-rosella-hightower", nom: "PNSD Rosella Hightower", type: "Établissement supérieur", ville: "Mougins", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.pnsd.fr/", parcours: ["Enseignement supérieur", "DNSP", "DE", "Danse-études", "Préprofessionnel", "Supérieur public"], programmes: ["DNSP", "DE", "Danse-Études"], statut: "Public" }),
  formation({ id: "ecole-nationale-danse-marseille", nom: "École Nationale de Danse de Marseille", type: "École", ville: "Marseille", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.endm.fr/", parcours: ["Danse-études", "Préprofessionnel", "Danseur interprète"], programmes: ["Danse-études", "Cycle Prépa Sup"] }),
  formation({ id: "cafedanse", nom: "CAFEDANSE", ville: "Aix-en-Provence", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.cafedanse.fr/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"] }),
  formation({ id: "coline-istres", nom: "Coline", type: "Compagnie", ville: "Istres", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.coline-istres.org/", parcours: ["Danseur interprète", "Insertion professionnelle", "Formation professionnelle"], programmes: ["Formation longue"], styles: ["Contemporain"] }),
  formation({ id: "arles-youth-ballet", nom: "Arles Youth Ballet Company", type: "Compagnie", ville: "Arles", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.arlesyouthballetcompany.com/", parcours: ["Jeune Ballet / Junior Ballet", "Préprofessionnel", "Danseur interprète"] }),
  formation({ id: "orchestra-pro-danse", nom: "Orchestra Pro Danse", ville: "Marseille", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://orchestra-pro.com/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Pluridisciplinaire"], duree: "2 ans" }),
  formation({ id: "off-jazz", nom: "Off Jazz / CFPESD", ville: "Nice", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://offjazz.com/", parcours: ["Formation professionnelle", "EAT", "DE", "Enseignement supérieur", "Supérieur privé"], styles: ["Jazz / modern jazz"], statut: "Privé" }),
  formation({ id: "melting-danse", nom: "Melting Danse – FDPI", ville: "Nice", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.meltingdanse.fr/", parcours: ["Danseur interprète", "Formation professionnelle"], styles: ["Pluridisciplinaire"] }),
  formation({ id: "millenium-dance-center", nom: "Millenium Dance Center – SCHÉMAS", ville: "Cagnes-sur-Mer", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://milleniumdancecenter.fr/", parcours: ["Formation professionnelle", "Préprofessionnel", "Danseur interprète"] }),
  formation({ id: "danse-mouvance", nom: "Centre Danse Mouvance", ville: "L’Isle-sur-la-Sorgue", region: "Provence-Alpes-Côte d’Azur", siteWeb: "https://www.dansemouvance.org/", parcours: ["Danseur interprète", "Formation professionnelle", "EAT", "DE"] }),
  formation({ id: "universite-corse", nom: "Université de Corse", type: "Université", ville: "Corte", region: "Corse", siteWeb: "https://www.universita.corsica/", parcours: ["Enseignement supérieur", "DE", "Supérieur public"], programmes: ["Formation supérieure", "DE danse"], styles: ["Contemporain", "Jazz / modern jazz"], statut: "Public" }),
  formation({ id: "format-danse", nom: "Format’Danse", ville: "Baie-Mahault", region: "Guadeloupe", parcours: ["Formation professionnelle", "DE"], styles: ["Classique", "Contemporain", "Jazz / modern jazz"] }),
  formation({ id: "conservatoire-brest", nom: "Conservatoire de Brest Métropole", type: "Conservatoire", ville: "Brest", region: "Bretagne", siteWeb: "https://conservatoire.brest.fr/les-cours/classe-preparatoire-lenseignement-superieur-cpes", parcours: ["CPES / COP", "Préprofessionnel", "Enseignement public"], programmes: ["CPES danse", "Classe préparatoire à l’enseignement supérieur", "COP danse", "Préparation au Diplôme d’Études Chorégraphiques (DEC)"], styles: ["Classique", "Jazz / modern jazz", "Contemporain"], duree: "CPES : 2 ans en moyenne · COP : 2 à 4 ans", statut: "Public", description: "Le CPES prépare aux concours de l’enseignement supérieur artistique. Le COP accompagne une orientation vers les études supérieures ou une activité professionnelle." }),
  formation({ id: "crr-rouen", nom: "Conservatoire à Rayonnement Régional de Rouen", type: "Conservatoire", ville: "Rouen", region: "Normandie", adresse: "50 avenue de la Porte des Champs, 76000 Rouen", siteWeb: "https://www.conservatoirederouen.fr/enseignement/danse/cursus/", parcours: ["CPES / COP", "Préprofessionnel", "Enseignement public"], programmes: ["CPES danse", "Préparation aux concours et formations supérieures professionnelles"], statut: "Public" }),
  formation({ id: "conservatoire-strasbourg", nom: "Conservatoire de Strasbourg", type: "Conservatoire", ville: "Strasbourg", region: "Grand Est", adresse: "1 place Dauphine, 67000 Strasbourg", siteWeb: "https://www.conservatoire.strasbourg.eu/", parcours: ["CPES / COP", "Préprofessionnel", "Enseignement public"], programmes: ["Cycle préparatoire à l’enseignement supérieur en danse"], styles: ["Classique", "Contemporain", "Jazz / modern jazz"], statut: "Public" }),
  formation({ id: "conservatoire-grand-poitiers", nom: "Conservatoire de Grand Poitiers", type: "Conservatoire", ville: "Poitiers", region: "Nouvelle-Aquitaine", siteWeb: "https://conservatoire.grandpoitiers.fr/danse/cursus/", parcours: ["CPES / COP", "Préprofessionnel", "Enseignement public"], programmes: ["CPES danse", "Cycle spécialisé"], statut: "Public" }),
  formation({ id: "espace-de-rue-grand-chalon", nom: "Espace des Arts / Grand Chalon", ville: "Chalon-sur-Saône", region: "Bourgogne-Franche-Comté", siteWeb: "https://www.espace-des-arts.com/fr/espace-de-rue", parcours: ["Formation professionnelle", "Danseur interprète", "Insertion professionnelle", "Professionnalisation"], programmes: ["Formation professionnelle danseur interprète hip-hop Espace de Rue"], styles: ["Hip-hop / danses urbaines"], description: "Formation agréée destinée aux danseuses et danseurs de 18 ans et plus souhaitant intégrer le monde professionnel." }),
  formation({ id: "jeune-ballet-ajaccien", nom: "Jeune Ballet Ajaccien", type: "Compagnie", ville: "Ajaccio", region: "Corse", siteWeb: "https://ajaccio.corsica/naissance-jeune-ballet-ajaccien/", parcours: ["Jeune Ballet / Junior Ballet", "Préprofessionnel", "Formation intensive"], programmes: ["Formation intensive destinée aux jeunes de 12 à 15 ans", "Parcours non diplômant de loisir intensif"], styles: ["Pluridisciplinaire"], description: "Dispositif municipal destiné aux jeunes danseuses et danseurs de 12 à 15 ans. Il s’agit d’un parcours intensif non diplômant, et non d’une formation professionnelle pour adultes.", statut: "Public" }),
  formation({ id: "ccnr", nom: "CCNR – Centre chorégraphique national de Rillieux-la-Pape", type: "Compagnie", ville: "Rillieux-la-Pape", region: "Auvergne-Rhône-Alpes", siteWeb: "https://www.ccnr.fr/yupi-la-jeune-compagnie-du-ccnr/", parcours: ["Jeune compagnie", "Insertion professionnelle", "Danseur interprète", "Professionnalisation"], programmes: ["YuPi – jeune compagnie du CCNR"], styles: ["Contemporain"], duree: "YuPi : 15 mois", statut: "Public" }),
]
