import type { EcoleDanse } from './ecoles-data'

const parisConservatory = (
  id: string,
  nom: string,
  adresse: string,
  arrondissement: number,
  siteWeb: string,
  styles: string[] = ['Danse'],
): EcoleDanse => ({
  id,
  nom,
  type: 'Conservatoire',
  adresse,
  ville: 'Paris',
  departement: 'Paris',
  region: 'Île-de-France',
  arrondissement,
  styles,
  categories: ['Conservatoires'],
  niveaux: [],
  pratiques: ['Enfants'],
  publics: ['Enfants et adolescents'],
  statut: 'Public',
  description: "Conservatoire municipal parisien d'enseignement artistique spécialisé, proposant un cursus de danse sur inscription.",
  siteWeb,
  sources: [siteWeb, 'https://www.paris.fr/dossiers/les-18-conservatoires-municipaux-240'],
})

/**
 * Annuaire parisien vérifié sur les sites officiels des établissements.
 * Les identifiants déjà présents enrichissent les fiches existantes lors de la fusion.
 */
export const parisDirectoryAdditions: EcoleDanse[] = [
  {
    id: 'studio-massaro', nom: 'Studio Massaro', type: 'Studio',
    adresse: '290 boulevard Voltaire, 75011 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 11, quartier: 'Nation',
    styles: ['Salsa', 'Bachata', 'Tango argentin', 'Hip-hop', 'Heels', 'Street jazz', 'Modern jazz', 'Dancehall', 'Waacking', 'Voguing', 'Afro dance', 'Pole dance'],
    niveaux: ['Débutant', 'Intermédiaire', 'Avancé', 'Professionnel'],
    pratiques: ['Loisirs', 'Formation professionnelle', 'Enfants', 'Adultes', 'Cours open'],
    publics: ['Enfants', 'Adolescents', 'Adultes', 'Professionnels'],
    categorie: 'Se former professionnellement', parcours: ['Formation professionnelle', 'Danseur interprète'], statut: 'Privé',
    description: 'École multistyles de Paris Nation proposant plus de trente disciplines, des cours tous niveaux et une formation professionnelle.',
    siteWeb: 'https://studio-massaro.fr/', sources: ['https://studio-massaro.fr/', 'https://studio-massaro.fr/ou-sommes-nous'],
    image: 'https://static.readdy.ai/image/75899d7db2b3a283c7bd7aabee24143d/9b3db9b764e73f7197aa933b17cb61e0.jpeg?ogv=1gdmz4w',
    imageAlt: 'Studio Massaro — image officielle de présentation',
  },
  {
    id: 'ifpro-rick-odums', nom: 'Centre International de Danse Rick Odums / IFPRO', type: 'Centre de formation',
    adresse: '54 A rue de Clichy, 75009 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 9, quartier: 'Clichy–Trinité',
    styles: ['Jazz', 'Modern jazz', 'Danse classique', 'Contemporain'],
    niveaux: ['Débutant', 'Intermédiaire', 'Avancé', 'Professionnel'],
    pratiques: ['Loisirs', 'Formation professionnelle', 'Préparation EAT/DE', 'Adultes', 'Cours open'],
    publics: ['Adultes', 'Professionnels'], categorie: 'Se former professionnellement',
    parcours: ['Formation professionnelle', 'Danseur interprète', 'EAT', 'DE'], statut: 'Privé',
    description: 'Centre international dédié à la danse jazz et institut de formation professionnelle pour les artistes interprètes et professeur.es.',
    siteWeb: 'https://centre-rick-odums.com/', sources: ['https://centre-rick-odums.com/contactez-nous/'],
  },
  {
    id: 'ze-art-studios', nom: 'ZE Art Studios', type: 'Studio',
    adresse: '17 rue Saint-Marc, 75002 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 2, quartier: 'Bourse',
    styles: ['Salsa', 'Danses de salon', 'Rock', 'West Coast Swing', 'Jive', 'Lindy hop', 'Hip-hop', 'Modern jazz', 'Danse classique'],
    niveaux: ['Débutant', 'Intermédiaire', 'Avancé'], pratiques: ['Loisirs', 'Enfants', 'Adultes'],
    publics: ['Enfants dès 3 ans', 'Adultes', 'Couples'], statut: 'Privé',
    description: 'École de danse et de bien-être proposant danses de couple, danses solo et cours enfants au cœur de Paris.',
    siteWeb: 'https://zeartstudios.com/', sources: ['https://zeartstudios.com/qui-sommes-nous/', 'https://zeartstudios.com/contact/'],
  },
  {
    id: 'ecole-danse-paris', nom: 'École de Danse de Paris', type: 'Centre de formation',
    adresse: '17 rue du Faubourg du Temple, 75010 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 10, quartier: 'République',
    styles: ['Danse classique', 'Jazz', 'Modern jazz', 'Contemporain'],
    niveaux: ['Débutant', 'Intermédiaire', 'Avancé', 'Professionnel'], pratiques: ['Formation professionnelle', 'Préparation EAT/DE', 'Adultes'],
    publics: ['Adultes', 'Professionnels'], categorie: 'Se former professionnellement', parcours: ['Formation professionnelle', 'EAT', 'DE'], statut: 'Privé',
    description: 'École et organisme de formation en danse installé à République, proposant des parcours de perfectionnement et de préparation professionnelle.',
    siteWeb: 'https://danse-a-paris.com/', sources: ['https://danse-a-paris.com/actualites/', 'https://danse-a-paris.com/wp-content/uploads/2024/02/Livret-daccueil.pdf'],
  },
  {
    id: 'ecole-danses-latines-tropicales', nom: 'École des Danses Latines et Tropicales', type: 'Centre de formation',
    adresse: '40 rue de Cîteaux, 75012 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 12,
    styles: ['Salsa', 'Bachata', 'Danses afro-caribéennes', 'Danses latines', 'Danses tropicales'],
    niveaux: ['Débutant', 'Intermédiaire', 'Avancé', 'Professionnel'], pratiques: ['Loisirs', 'Formation professionnelle', 'Adultes'],
    publics: ['Adultes', 'Professionnels'], categorie: 'Se former professionnellement', parcours: ['Formation professionnelle'], statut: 'Privé',
    description: 'École spécialisée dans les danses afro-caribéennes et latines, avec cours collectifs, individuels et centre de formation professionnelle.',
    siteWeb: 'https://www.salsadanse.com/', sources: ['https://www.salsadanse.com/ecole-de-danse-latines-tropicales/'],
  },
  {
    id: 'ecole-danse-opera-paris', nom: "École de Danse de l'Opéra national de Paris", type: 'Établissement supérieur',
    adresse: '20 allée de la Danse, 92000 Nanterre', ville: 'Nanterre', departement: 'Hauts-de-Seine', region: 'Île-de-France',
    styles: ['Danse classique'], niveaux: ['Avancé', 'Professionnel'], pratiques: ['Formation professionnelle', 'Enfants'],
    publics: ['Jeunes danseuses et danseurs admis sur concours'], categorie: 'Se former professionnellement',
    parcours: ['Formation professionnelle', 'Danse-études', 'Préprofessionnel'], statut: 'Public',
    description: "École professionnelle du Ballet de l'Opéra national de Paris, implantée à Nanterre et accessible sur concours.",
    siteWeb: 'https://www.operadeparis.fr/artistes/ecole-de-danse', sources: ['https://www.operadeparis.fr/artistes/ecole-de-danse'],
  },

  parisConservatory('conservatoire-mozart-centre', 'Conservatoire W. A. Mozart Paris Centre', '7 passage de la Canopée, 75001 Paris', 1, 'https://www.paris.fr/lieux/conservatoire-municipal-w-a-mozart-centre-1595', ['Danse classique', 'Danse contemporaine', 'Jazz', 'Hip-hop', 'Claquettes']),
  parisConservatory('conservatoire-gabriel-faure', 'Conservatoire Gabriel Fauré', '12 rue de Pontoise, 75005 Paris', 5, 'https://www.paris.fr/lieux/conservatoire-municipal-gabriel-faure-1596'),
  parisConservatory('conservatoire-rameau', 'Conservatoire Jean-Philippe Rameau', '3 ter rue Mabillon, 75006 Paris', 6, 'https://www.paris.fr/lieux/conservatoire-municipal-jean-philippe-rameau-1597'),
  parisConservatory('conservatoire-erik-satie', 'Conservatoire Erik Satie', "135 bis rue de l'Université, 75007 Paris", 7, 'https://www.paris.fr/lieux/conservatoire-municipal-erik-satie-1599'),
  parisConservatory('conservatoire-camille-saint-saens', 'Conservatoire Camille Saint-Saëns', '208 rue du Faubourg Saint-Honoré, 75008 Paris', 8, 'https://www.paris.fr/lieux/conservatoire-municipal-camille-saint-saens-1602'),
  parisConservatory('conservatoire-nadia-lili-boulanger', 'Conservatoire Nadia et Lili Boulanger', '17 rue de Rochechouart, 75009 Paris', 9, 'https://www.paris.fr/lieux/conservatoire-municipal-nadia-et-lili-boulanger-1604'),
  parisConservatory('conservatoire-hector-berlioz', 'Conservatoire Hector Berlioz', '6 rue Pierre Bullet, 75010 Paris', 10, 'https://www.paris.fr/lieux/conservatoire-municipal-hector-berlioz-1607'),
  parisConservatory('conservatoire-charles-munch', 'Conservatoire Charles Munch', '7 rue Duranti, 75011 Paris', 11, 'https://www.paris.fr/lieux/conservatoire-municipal-charles-munch-1608'),
  parisConservatory('conservatoire-paul-dukas', 'Conservatoire Paul Dukas', '51 rue Jorge Semprún, 75012 Paris', 12, 'https://www.paris.fr/lieux/conservatoire-municipal-paul-dukas-1815'),
  parisConservatory('conservatoire-maurice-ravel', 'Conservatoire Maurice Ravel', '67 avenue Edison, 75013 Paris', 13, 'https://www.paris.fr/lieux/conservatoire-municipal-maurice-ravel-1615'),
  parisConservatory('conservatoire-darius-milhaud', 'Conservatoire Darius Milhaud', '2 impasse Vandal, 75014 Paris', 14, 'https://www.paris.fr/lieux/conservatoire-municipal-darius-milhaud-1616'),
  parisConservatory('conservatoire-frederic-chopin', 'Conservatoire Frédéric Chopin', '43 rue Bargue, 75015 Paris', 15, 'https://www.paris.fr/lieux/conservatoire-municipal-frederic-chopin-1620'),
  parisConservatory('conservatoire-francis-poulenc', 'Conservatoire Francis Poulenc', '11 rue Jean de La Fontaine, 75016 Paris', 16, 'https://www.paris.fr/lieux/conservatoire-municipal-francis-poulenc-1623'),
  parisConservatory('conservatoire-claude-debussy', 'Conservatoire Claude Debussy', '222 rue de Courcelles, 75017 Paris', 17, 'https://www.paris.fr/lieux/conservatoire-municipal-claude-debussy-site-courcelles-1626'),
  parisConservatory('conservatoire-gustave-charpentier', 'Conservatoire Gustave Charpentier', '29 rue Baudelique, 75018 Paris', 18, 'https://www.paris.fr/lieux/conservatoire-municipal-gustave-charpentier-1629'),
  parisConservatory('conservatoire-jacques-ibert', 'Conservatoire Jacques Ibert', '81 rue Armand Carrel, 75019 Paris', 19, 'https://www.paris.fr/lieux/conservatoire-municipal-jacques-ibert-1631'),
  parisConservatory('conservatoire-georges-bizet', 'Conservatoire Georges Bizet', '3 place Carmen, 75020 Paris', 20, 'https://www.paris.fr/lieux/conservatoire-municipal-georges-bizet-1635'),
  {
    id: 'crr-paris-ida-rubinstein', nom: 'CRR de Paris – Ida Rubinstein', type: 'Conservatoire',
    adresse: '8 rue Véron, 75018 Paris', ville: 'Paris', departement: 'Paris', region: 'Île-de-France', arrondissement: 18, quartier: 'Montmartre',
    styles: ['Danse classique', 'Contemporain', 'Jazz'], categories: ['Conservatoires', 'Formation professionnelle'],
    niveaux: ['Intermédiaire', 'Avancé', 'Professionnel'], pratiques: ['Formation professionnelle', 'Enfants', 'Adultes'],
    publics: ['Collégiens', 'Lycéens', 'Post-bac'], categorie: 'Se former professionnellement',
    parcours: ['Préprofessionnel', 'CPES / COP', 'Danse-études', 'Supérieur public'], programmes: ['Second cycle', 'Cycle spécialisé', 'CPES danse'], statut: 'Public',
    description: 'Le département danse du CRR propose des cursus classique, contemporain et jazz, du second cycle au CPES et au double cursus.',
    siteWeb: 'https://www.paris.fr/pages/la-danse-au-crr-de-paris-ida-rubinstein-31753', sources: ['https://www.paris.fr/pages/la-danse-au-crr-de-paris-ida-rubinstein-31753'],
  },
]
